;Kameron Gill
;1476833
;kgill2@ucsc.edu

;Tues/Thurs 7-9PM
;Lab 4 : Cipher decryption

.ORIG x300

LEA R0, GREETINGS   ;R0=>GREETING MESSAGE
PUTS                ;PRINTS GREETING MESSAGE

;RESET ALL MEMORY COUNTERS
START R0, R0, #0
      AND R1, R1, #0    ;FLAG
      AND R2, R2, #0    ;INT
      AND R3, R3, #0    COUNT
      AND R4, R4, #0
      AND R5, R5, #0
      AND R6, R6, #0
      AND R7, R7, #0    ;TEMP

LEA R0, TYPE      ;R0=>D/ECRPYT QUESTION
PUTS              ;PRINTS QUESTION

GETC      ;INPUT
OUT

;DECREPT ENCRYPT OR EXIT CHECKERS

;ENCRYPT
LD R4, CHECKE   ;R4=>-69
ADD R2, R0, R4  ;R2=INPUT(R0)+(-69)
BRz CIPHER        ;IF R2==0 => CIPHER FUNCTION

;DECRYPT
LD R4, CHECKD   ;R4=>-68
ADD R2, R0, R4  ;R2=INPUT+(-68)
BRz CIPHER

;EXIT
LD R4, CHECKX   ;R4=>-88
ADD R2, R0, R4  ;R2=INPUT+(-88)
BRz EXIT        ;R2==0 =>EXIT

;ERROR CHECK
BRnp START      ;IF D E X NOT HIT, REPEAT

;ENCRYPT OR DECRYPT
FLAG1 ADD R1, R1, #1
ST R1, FLAG
AND R1, R1, 0


CIPHER    LEA R0, WHATNUM ;R0 SET TO WHAT CIPHER #
          PUTS            ;PRINTS OUT QUESTION FOR CIPHER
NUMBER GETC               ;GETS NEXT USER INPUT
OUT
LD R4, #-10       ;R4=> NEWLINE INVERT
ADD R2, R0, R4    ;R2+INPUT+-(-10)
BRz DECRYPT


;VARIABLES
ECHECK .FILL #-69     ;E
DCHECK .FILL #-68     ;D
XCHECK .FILL #-88     ;X
FLAG .FILL #0         ;FLAG
;STRINGS
GREETING STRINGZ "WELCOME TO LAB4"
TYPE .STRINGZ "Would you like to (E)ncrypt, (D)ecrpyt, or (X)it?"
WHATNUM .STRINGZ "Pick a cipher from 1-25"
REULT: "Here is your string and decrypted result:"

.END
